package skuber.operator.crd

import play.api.libs.json.{Format, OFormat, OWrites, JsNull, JsObject, JsPath, JsResult, JsValue, JsError}
import play.api.libs.functional.syntax._
import skuber.model.{
  CustomResource, HasStatusSubresource, ObjectMeta, ObjectResource, ResourceDefinition, ResourceSpecification
}
import skuber.model.ac.{ApplyConfiguration, ObjectMetaApplyConfig}

/** Format for Nothing - used by spec-only resources where status is None */
private[crd] given nothingFormat: Format[Nothing] = new Format[Nothing]:
  def reads(json: JsValue): JsResult[Nothing] = JsError("Nothing cannot be read")
  def writes(o: Nothing): JsValue = JsNull

/**
 * Generic server-side-apply configuration for custom resources.
 *
 * CRD specs are represented as a JsObject fragment rather than the normal Spec case class so callers can
 * include exactly the fields they want this field manager to own. Omitted fields are not written and are
 * therefore not claimed by SSA.
 */
case class CustomResourceApplyConfig[O <: ObjectResource](
  kind: String,
  apiVersion: String,
  metadata: Option[ObjectMetaApplyConfig] = None,
  spec: Option[JsObject] = None
) extends ApplyConfiguration[O]:
  def name: String = metadata.flatMap(_.name).getOrElse("")

  def withMetadata(m: ObjectMetaApplyConfig): CustomResourceApplyConfig[O] =
    copy(metadata = Some(m))

  def withSpec(s: JsObject): CustomResourceApplyConfig[O] =
    copy(spec = Some(s))

  def addLabel(kv: (String, String)): CustomResourceApplyConfig[O] =
    copy(metadata = Some(metadata.getOrElse(ObjectMetaApplyConfig()).addLabel(kv)))

  def addAnnotation(kv: (String, String)): CustomResourceApplyConfig[O] =
    copy(metadata = Some(metadata.getOrElse(ObjectMetaApplyConfig()).addAnnotation(kv)))

object CustomResourceApplyConfig:
  given writes[O <: ObjectResource]: OWrites[CustomResourceApplyConfig[O]] = (
    (JsPath \ "kind").write[String] and
    (JsPath \ "apiVersion").write[String] and
    (JsPath \ "metadata").writeNullable[ObjectMetaApplyConfig] and
    (JsPath \ "spec").writeNullable[JsObject]
  )(c => (c.kind, c.apiVersion, c.metadata, c.spec))

/**
 * Base trait for custom resources with only a Spec (no Status).
 * Provides type alias, factory method, and ResourceDefinition.
 */
trait CustomResourceSpecDef[S]:
  /** The concrete CustomResource type for this definition */
  final type Resource = CustomResource[S, Nothing]

  /** Abstract val for Spec format - usually auto generated by @customResource macro but can be overridden if customisation needed */
  protected val specFormat: OFormat[S]

  /** JSON format for the Spec type as exposed to client - delegates to above */
  given theSpecFormat: OFormat[S] = specFormat

  /** Metadata tuple: (kind, group, version, plural, singular, shortNames, scope) - implemented by macro */
  def crMetadata: (String, String, String, String, String, List[String], String)

  /** Create a new custom resource instance with the given name and spec */
  def apply(name: String, spec: S): Resource =
    val (kind, group, version, _, _, _, _) = crMetadata
    CustomResource[S, Nothing](kind, s"$group/$version", ObjectMeta(name = name), spec, None)

  /**
   * Create a server-side-apply configuration for this custom resource.
   * Add desired spec fields with `.withSpec(Json.obj(...))`; omitted fields are not claimed by SSA.
   */
  def applyConfig(name: String): CustomResourceApplyConfig[Resource] =
    val (kind, group, version, _, _, _, _) = crMetadata
    CustomResourceApplyConfig[Resource](
      kind = kind,
      apiVersion = s"$group/$version",
      metadata = Some(ObjectMetaApplyConfig(name = Some(name)))
    )

  /** Create a server-side-apply configuration with a partial spec object. */
  def applyConfig(name: String, spec: JsObject): CustomResourceApplyConfig[Resource] =
    applyConfig(name).withSpec(spec)

  /** ResourceDefinition for API calls */
  given resourceDefinition: ResourceDefinition[Resource] =
    val (kind, group, version, plural, singular, shortNames, scopeStr) = crMetadata
    val scope = if scopeStr == "Cluster" then ResourceSpecification.Scope.Cluster
                else ResourceSpecification.Scope.Namespaced
    ResourceDefinition[Resource](
      kind = kind,
      group = group,
      version = version,
      singular = Some(singular),
      plural = Some(plural),
      scope = scope,
      shortNames = shortNames
    )

  /** JSON format for the CustomResource type */
  given resourceFormat(using Format[S]): Format[Resource] =
    CustomResource.crFormat[S, Nothing]

/**
 * Trait for custom resources with both Spec and Status.
 * This is a separate trait (not extending CustomResourceSpecDef) to avoid type conflicts.
 */
trait CustomResourceDef[S, St]:
  /** The concrete CustomResource type for this definition */
  final type Resource = CustomResource[S, St]

  /** Underlying Spec JSON formatter - usually auto generated by @customResource macro but can be overridden in subclass */
  protected val specFormat: OFormat[S]

  /** Underlying Status JSON formatter - usually auto generated by @customResource macro but can be overridden in subclass */
  protected val statusFormat: OFormat[St]

  /** JSON format for the Spec type - delegates to above */
  given theSpecFormat: OFormat[S] = specFormat

  /** JSON format for the Status type - delegates to above */
  given theStatusFormat: OFormat[St] = statusFormat

  /** Metadata tuple: (kind, group, version, plural, singular, shortNames, scope) - implemented by macro */
  def crMetadata: (String, String, String, String, String, List[String], String)

  /** Create a new custom resource instance with the given name and spec */
  def apply(name: String, spec: S): Resource =
    val (kind, group, version, _, _, _, _) = crMetadata
    CustomResource[S, St](kind, s"$group/$version", ObjectMeta(name = name), spec, None)

  /**
   * Create a server-side-apply configuration for this custom resource.
   * Add desired spec fields with `.withSpec(Json.obj(...))`; omitted fields are not claimed by SSA.
   */
  def applyConfig(name: String): CustomResourceApplyConfig[Resource] =
    val (kind, group, version, _, _, _, _) = crMetadata
    CustomResourceApplyConfig[Resource](
      kind = kind,
      apiVersion = s"$group/$version",
      metadata = Some(ObjectMetaApplyConfig(name = Some(name)))
    )

  /** Create a server-side-apply configuration with a partial spec object. */
  def applyConfig(name: String, spec: JsObject): CustomResourceApplyConfig[Resource] =
    applyConfig(name).withSpec(spec)

  /** ResourceDefinition for API calls */
  given resourceDefinition: ResourceDefinition[Resource] =
    val (kind, group, version, plural, singular, shortNames, scopeStr) = crMetadata
    val scope = if scopeStr == "Cluster" then ResourceSpecification.Scope.Cluster
                else ResourceSpecification.Scope.Namespaced
    ResourceDefinition[Resource](
      kind = kind,
      group = group,
      version = version,
      singular = Some(singular),
      plural = Some(plural),
      scope = scope,
      shortNames = shortNames
    )

  /** JSON format for the CustomResource type */
  given resourceFormat(using Format[S], Format[St]): Format[Resource] =
    CustomResource.crFormat[S, St]

  /** Enables getStatus/updateStatus API methods */
  given statusSubresource: HasStatusSubresource[Resource] =
    new HasStatusSubresource[Resource] {}
